# Requires docker-compose >= 1.29.0
version: '3.9'

services:
  gw-readonly:
    container_name: gw-testnet_v1.1-readonly
    image: ghcr.io/nervosnetwork/godwoken-prebuilds:v1.1.3-beta-202205231016
    healthcheck:
      test: /healthcheck.sh
      start_period: 10s
      interval: 30s
      retries: 100000
    working_dir: /deploy
    volumes:
    - ./chain-data/readonly/:/mnt/
    - ./gw-testnet_v1.1-config-readonly.toml:/deploy/config.toml
    - ./db.toml:/deploy/db.toml:ro
    - ./block_producer.key:/deploy/block_producer.key:ro
    - ./healthcheck.sh:/healthcheck.sh:ro
    environment:
    # other log envs: ,gw_generator=debug,gw_chain=debug
    - RUST_LOG=info
    command: godwoken
    expose:
    - 8119
    - 8219

  postgres:
    image: postgres:alpine
    expose:
    - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
    - ./chain-data/postgresql/data:/var/lib/postgresql/data
  
  redis:
    image: redis:bullseye
    user: redis:redis
    volumes:
    - ./chain-data/redis-data:/data

  web3:
    image: ghcr.io/nervosnetwork/godwoken-web3-prebuilds:refactor-db-01b5da5
    healthcheck:
      test: curl http://127.0.0.1:8024 || exit 1
    volumes:
    - ./web3.env:/godwoken-web3/packages/api-server/.env
    working_dir: /godwoken-web3
    command: bash -c 'set -ex ; yarn knex migrate:latest && yarn start:prod'
    ports:
    - 8024
    depends_on:
    - redis
    - postgres
    - gw-readonly

  web3-indexer:
    image: ghcr.io/nervosnetwork/godwoken-web3-indexer-prebuilds:refactor-db-01b5da5
    volumes:
    - ./web3-indexer-config.toml:/var/lib/web3-indexer/indexer-config.toml
    working_dir: /var/lib/web3-indexer
    command: [ "gw-web3-indexer" ]
    environment:
    - RUST_LOG=info
    depends_on:
      web3:
        condition: service_healthy
      gw-readonly:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
